name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          username: rocket
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/projects/home.rocket
            git pull
            cd homepage-stack
            docker rm -f homepage || true
            docker compose up -d
            echo "✅ Déploiement terminé avec succès !"
